workspace './application.xcworkspace'
platform :ios, '14.0'

load "./dependencies.rb"

#Target modules
modulesDependencies = Set.new
modulesDependencies.merge(addTarget(self, "../module_root"))
modulesDependencies.merge(addTarget(self, "../module_feature_a"))
modulesDependencies.merge(addTarget(self, "../module_feature_b"))

#Target configuration
puts "** Add target application"
target 'application' do
  project './application.xcodeproj'
  use_frameworks!
  
  puts "+ herited from modules"
  modulesDependencies.each do |dependency|
    puts "- #{dependency}"
    library(self, dependency)
  end
  
end
