workspace './application.xcworkspace'
platform :ios, '14.0'

#Dependencies
def pod_swiftdate
  pod 'SwiftDate', :git=> 'https://github.com/malcommac/SwiftDate.git', :tag => '7.0.0'
end

#Target configuration
target 'application' do
  project './application.xcodeproj'
  use_frameworks!
  
#  pod_swiftdate
  
end


target 'module_root' do
  project '../module_root/module_root.xcodeproj'
  use_frameworks!
  
  pod_swiftdate

end


target 'module_feature_a' do
  project '../module_feature_a/module_feature_a.xcodeproj'
  use_frameworks!

end


target 'module_feature_b' do
  project '../module_feature_b/module_feature_b.xcodeproj'
  use_frameworks!

end
